"""Central project paths. The one place to change locations.

Change ``OUTPUTS_DIR`` to relocate everything generated by training, export and
logging. ``resolve_output`` maps a relative path under ``OUTPUTS_DIR`` (absolute
paths pass through unchanged).
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Version-controlled inputs.
CONFIGS_DIR = PROJECT_ROOT / "configs"
FONTS_DIR = PROJECT_ROOT / "fonts"
LABELS_FILE = PROJECT_ROOT / "labels.txt"
JP_FONT = FONTS_DIR / "NotoSerifCJKjp-Regular.otf"

# Generated outputs (all under one directory).
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
RUNS_DIR = OUTPUTS_DIR / "runs"
EXPORTS_DIR = OUTPUTS_DIR / "exports"
MLRUNS_DIR = OUTPUTS_DIR / "mlruns"


def resolve_output(path: str | Path) -> Path:
    """Resolve ``path`` under ``OUTPUTS_DIR``; absolute paths are returned as-is."""
    p = Path(path)
    return p if p.is_absolute() else OUTPUTS_DIR / p
